return {
    scrap_metal = {
        Name = "Scrap Metal",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    rusted_iron = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    iron_ore = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    iron_ingot = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    steel = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    copper_ore = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    copper_ingot = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    eletronic_parts = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    circuit_board = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    solar_cell = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    battery_cell = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    fuel_canister = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    crystal_shard = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    meteorite = {
        Name = "",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
}