return {
    scrap_metal = {
        Name = "Scrap Metal",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    rusted_iron = {
        Name = "Rusted Iron",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    iron_ore = {
        Name = "Iron Ore",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    iron_ingot = {
        Name = "Iron Ingot",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    steel = {
        Name = "Steel",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    copper_ore = {
        Name = "Copper Ore",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    copper_ingot = {
        Name = "Copper Ingot",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    eletronic_parts = {
        Name = "Eletronic Parts",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    circuit_board = {
        Name = "Circuit Board",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    solar_cell = {
        Name = "Solar Cell",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    battery_cell = {
        Name = "Battery Cell",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    fuel_canister = {
        Name = "Fuel Canister",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    crystal_shard = {
        Name = "Crystal Shard",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
    meteorite = {
        Name = "Meteorite",
        Category = "Resource",
        Rarity = "Common",
        StackSize = 99
    },
}