return {
	["Basic"] = {
		Name = "Basic",
		Boost = false,
		Production = 1,
		ConnectedTo = nil :: Instance?,
		Position = nil :: Vector3?,
		Craft = { iron_ingot = 10, solar_cell = 10, eletronic_parts = 2 },
	},
	["Intermediate"] = {
		Name = "Intermediate",
		Boost = false,
		Production = 1,
		ConnectedTo = nil :: Instance?,
		Position = nil :: Vector3?,
		Craft = { iron_ingot = 10, solar_cell = 10, eletronic_parts = 2 },
	},
	["Advanced"] = {
		Name = "Advanced",
		Boost = false,
		Production = 1,
		ConnectedTo = nil :: Instance?,
		Position = nil :: Vector3?,
		Craft = { iron_ingot = 10, solar_cell = 10, eletronic_parts = 2 },
	},
}
