-- modux ignore file
export type AlienType =
	"Common"
| "Intermediate"
| "Runner"
| "Rage"
| "Telekinesis"
| "Screamer"
| "Shooter"
| "Knifer"
| "Sniper"
| "Tanker"
| "Brutus"
| "AlienAnimal"

export type AliensEnum = {
	Common: "Common",
	Intermediate: "Intermediate",
	Runner: "Runner",
	Rage: "Rage",
	Telekinesis: "Telekinesis",
	Screamer: "Screamer",
	Shooter: "Shooter",
	Knifer: "Knifer",
	Sniper: "Sniper",
	Tanker: "Tanker",
	Brutus: "Brutus",
	AlienAnimal: "AlienAnimal",
}

return {
	Common = "Common",
	Intermediate = "Intermediate",
	Runner = "Runner",
	Rage = "Rage",
	Telekinesis = "Telekinesis",
	Screamer = "Screamer",
	Shooter = "Shooter",
	Knifer = "Knifer",
	Sniper = "Sniper",
	Tanker = "Tanker",
	Brutus = "Brutus",
	AlienAnimal = "AlienAnimal",
} :: AliensEnum
