export type AliensTypes = {
	Common: "Common",
	Intermediate: "Intermediate",
	Runner: "Runner",
	Rage: "Rage",
	Telekinesis: "Telekinesis",
	Screamer: "Screamer",
	Shooter: "Shooter",
	Knifer: "Knifer",
	Sniper: "Sniper",
	Tanker: "Tanker",
	Brutus: "Brutus",
	AlienAnimal: "AlienAnimal",
}

return {
	Common = "Common",
	Intermediate = "Intermediate",
	Runner = "Runner",
	Rage = "Rage",
	Telekinesis = "Telekinesis",
	Screamer = "Screamer",
	Shooter = "Shooter",
	Knifer = "Knifer",
	Sniper = "Sniper",
	Tanker = "Tanker",
	Brutus = "Brutus",
	AlienAnimal = "AlienAnimal",
} :: AliensTypes
